### ISSUE TITLE
Update svg loader to avoid loading svg fonts

### ISSUE THREAD

**Issue by antoniocapelo** [moxystudio/react-with-moxy#46]
The current webpack config is ignoring `.svg` files in a specific directory. If a user places fonts with a svg version in a different place than that, they get included on the sprite and that will cause the client-side to reference a svg sprite different than the one created.

The `svg loader` ignore rule should be updated to avoid this situation.

**Comment by satazor** [comment]
The initial reasoning was that fonts should live in shared/media/fonts but that folder didn't exist. 

We can either:
- Add a shared/media/fonts to the boilerplate
- Update the ignore pattern to ignore filenames that have font in its path

I actually prefer the first so that we have a standard place to put fonts across projects, just as we have a folder to place css mixins.

Let me know what you think.

**Comment by antoniocapelo** [comment]
@satazor I agree, the first option defines a standard for future projects and we can exclude that directory by the `svg` loader.
